### ISSUE TITLE
0.58.4 Discussion

### ISSUE THREAD

**Issue by grabbou** [react-native-community/react-native-releases#86] opened 2019-02-07 11:44 UTC
Conversation on this thread are limited to 0.58.0 release's major issues and backport (cherry-pick) requests from commits that are already on master.

An example of a good such request is a bug fix for a serious issue that has been merged into master but did not make the 0.58.4 cut.

In other words, if you cannot point to a particular commit on master, then your request likely belongs as a new issue in [http://github.com/facebook/react-native/issues](https://github.com/facebook/react-native/issues).

If the commit you request to cherry pick is a complicated port, you will be asked to create the PR to the 0.58-stable branch yourself, in order to ensure that the process proceeds smoothly.

**Comment by afilp** [comment] 2019-02-07 13:23
https://github.com/facebook/react-native/commit/f3e5cce4745c0ad9a5c697be772757a03e15edc5

Thanks!

**Comment by kelset** [comment] 2019-02-07 17:50
This is going to help with the TextInput issues -> https://github.com/facebook/react-native/commit/f307ac7c5e3adb9b4c0f8b2e4b8cdc2f980c7733

**Comment by grabbou** [comment] 2019-02-07 18:09
@aflip, we have already discussed this in #41 and came to the agreement that cherry-picking this commit could greatly affect the stability of 0.58 release. 

It's going to be in 0.59, which isn't far away. Please subscribe to #79 issue for further details.

**Comment by noahtallen** [comment] 2019-02-07 19:19
How about this one? https://github.com/facebook/react-native/commit/dda2b82a0a49da52b43b50db5a2bda50a216c09b

**Comment by afilp** [comment] 2019-02-08 09:25
@grabbou Sorry, I missed that part. Thank you!

**Comment by davidglivar** [comment] 2019-02-09 17:56
Fixes build issues for iOS -> https://github.com/facebook/react-native/commit/2aa24017667721ba17a859ca4e13d43e52d86bc5

**Comment by MeisiLA** [comment] 2019-02-11 13:13
Another build issue fix for iOS -> [facebook/react-native@ce5f9b1](https://github.com/facebook/react-native/commit/ce5f9b12e0fb48b3ca976d50ef91900a681d39de)

**Comment by elucaswork** [comment] 2019-02-12 18:19
Fix textTransform when used with other text styles on Android - https://github.com/facebook/react-native/commit/3a33e75183bf196d61b46e662b4c3f84a5f570bd

**Comment by dulmandakh** [comment] 2019-02-14 05:02
network security configuration for people who change targetSDK to 28 in build.gradle -
https://github.com/facebook/react-native/commit/5747094532bace3fe6b1ebdf55235e53189baa71

**Comment by mikehardy** [comment] 2019-02-14 15:34
@dulmandakh this is showing up when I look at the patches - https://github.com/pvinis/rn-diff-purge/compare/version/0.58.4...version/0.59.0-rc.0 - it appears to be incorporated already?

**Comment by dulmandakh** [comment] 2019-02-14 16:58
Yep, it's in 0.59, so I proposed it for 0.58.5 if released. I learned that
people are changing targetSDK to 28 and having network issues with 0.58
release, because Android Studio is suggesting to use the latest or 28
version.

>

**Comment by andresmtz98** [comment] 2019-02-14 21:32
> Yep, it's in 0.59, so I proposed it for 0.58.5 if released. I learned that people are changing targetSDK to 28 and having network issues with 0.58 release, because Android Studio is suggesting to use the latest or 28 version.
> […](#)

Yes, it will be pretty good if you release .58.5 for the Android issues with sdk 28.

**Comment by karanjthakkar** [comment] 2019-02-16 03:15
If there is going to be a 0.58.5, can we please get this in too: https://github.com/react-native-community/react-native-releases/issues/79#issuecomment-46424194?

**Comment by Eddie-CooRo** [comment] 2019-02-16 08:41
Fix Inverted Horizontal ScrollView on Android -> https://github.com/facebook/react-native/commit/4521cffc2c9448818f7a2f4a15808674c8f92069

**Comment by Jyrno42** [comment] 2019-02-16 16:19
I would love if this made it to the 0.58.x release https://github.com/facebook/react-native/commit/7795a672d3a24a5b50df6ad6d30555d856b557cc

**Comment by grabbou** [comment] 2019-02-17 07:03
I will be releasing another 0.58 release tomorrow with the commits mentioned.

**Comment by grabbou** [comment] 2019-02-18 13:53
Cherry-picked almost all the commits.

@Jyrno42, your commit is already part of the release.
@dulmandakh, your commit depends on another one. I have wrote you a DM to resolve the conflicts.
@noahtallen, I didn't cherry-pick your commit since it's already part of 0.59 where it's been deprecated too. I think it's good to not cherry-pick deprecations. I hope it's not a deal breaker for you.

**Comment by noahtallen** [comment] 2019-02-18 13:55
@grabbou no problem! That certainly makes sense. My hope was that it would help with a different issue I was having related to react native screens.

**Comment by grabbou** [comment] 2019-02-18 13:56
I understand! In this case, one thing I can do for you is to encourage you to try the RC :)

**Comment by cihati** [comment] 2019-02-18 16:03
(I apologize, I still haven't figured out how it's decided that certain commits are put into certain releases. Any pointers would be helpful)

@grabbou Any chance to get https://github.com/facebook/react-native/pull/22439 into the next release, assuming there will be 0.58.5 release? It's merged on Jan 2nd, and our app crashes a lot due to this issue. I see that the fix's already in the 0.59 branch: https://github.com/facebook/react-native/blob/0.59-stable/Libraries/WebSocket/RCTSRWebSocket.m

**Comment by mikehardy** [comment] 2019-02-18 16:06
@cihati I think you just ask for a specific commit, like so https://github.com/facebook/react-native/commit/dd209bb7891ed5f05b96a9922c7b0e39bf3ac9e9 in this case?

**Comment by cihati** [comment] 2019-02-18 16:10
Yes, that's the commit -- sorry I put the PR link initially instead.

**Comment by grabbou** [comment] 2019-02-18 16:11
I'll include that one too, just doing final touches before the release.

**Comment by cihati** [comment] 2019-02-18 20:24
@grabbou many thanks!! Just for my understanding: what's the release process timeline like in general? For instance, I see that you bumped version numbers to 0.58.5 ~4 hours ago ( https://github.com/facebook/react-native/commit/9d9069674a4ae71fa8762b08933acee08c7d5b04 ) but I don't see the new react-native version in NPM yet.

**Comment by grabbou** [comment] 2019-02-19 09:59
Generally speaking, it takes an hour from the tag pushed to Github to land on npm. Unfortunately, the CircleCI failed to checkout the code (https://circleci.com/gh/facebook/react-native/73354). I am investigating the issue.

**Comment by grabbou** [comment] 2019-02-19 15:10
The CI is back green and 0.58.5 is out.

**Comment by andresmtz98** [comment] 2019-02-19 15:38
Hmm the problem with internet connection on Android still persists  with sdk 28 :(. Or there is any config to do?

**Comment by kelset** [comment] 2019-02-19 15:52
@andresmtz98 can you comment on the related issue on the main repo? So that we can close this, open a new one for 0.58.6 if we decide to do a next one (before 0.59.0).

(also, you should double check that the issue is still present on the 0.59 rc)

**Comment by kelset** [comment] 2019-02-20 09:47
Closing in favor of -> https://github.com/react-native-community/react-native-releases/issues/95

**Closed by kelset** 2019-02-20 09:47 UTC
Labels: backport request, stable
