### ISSUE TITLE
0.57.3 Discussion

### ISSUE THREAD

**Issue by grabbou** [react-native-community/react-native-releases#48] opened 2018-10-11 21:40 UTC
Conversation on this thread are limited to 0.57.3 release's major issues and backport (cherry-pick) requests from commits that are already on master - so that we can then produce a 0.57.4 release in the near future.

An example of a good such request is a bug fix for a serious issue that has been merged into master but did not make the 0.57.3 cut.

In other words, if you cannot point to a particular commit on master, then your request likely belongs as a new issue in http://github.com/facebook/react-native/issues.

**Comment by TopGuo** [comment] 2018-10-12 02:31
If used for company production development, which react native version is more stable?

**Comment by ahce** [comment] 2018-10-12 06:54
@grabbou when release 0.57.3 in npm?

**Comment by kelset** [comment] 2018-10-12 09:06
Hey everyone, there was an issue with the release, I'm looking into it today

**Comment by grabbou** [comment] 2018-10-13 05:58
We should cherry-pick https://github.com/facebook/react-native/commit/b44c5ae92eb08125d466cf151cb804dabfbbc690 to improve Xcode 10 support and make sure it's all good at the time of 0.58 release.

**Comment by peat-psuwit** [comment] 2018-10-13 06:53
Please cherry-pick [Update link command for Android project](https://github.com/facebook/react-native/commit/4dfdec9). This commit fixes Android project auto-linking to be compatible with already-released Gradle plugin upgrade.

**Comment by matt-block** [comment] 2018-10-13 07:06
@peat-psuwit that update did not cover unlinking, so I think it should only be cherry-picked together with the [unlink PR](https://github.com/facebook/react-native/pull/21043) when it lands.

**Comment by peat-psuwit** [comment] 2018-10-13 07:14
@matt-block I agree with you. Thank you for pointing it out!

**Comment by radeno** [comment] 2018-10-13 14:16
@grabbou maybe we should have one up-to-date comment with approved cherry-pick commits. Like in forums where first topic comment is always updated (eg instructions to install something for current app version). Something like: https://github.com/react-native-community/react-native-releases/issues/46#issuecomment-428747211 What do you think? It allows us to update changelog continuously.

Anyway some patch commits:
- Android NDK r17c https://github.com/facebook/react-native/commit/436cf154bb9cf4fc0bcafd7115d33544ce36b759
- Avoid calling lazilyLoadView when running in the debugger https://github.com/facebook/react-native/commit/4f757095a8fdf28c6d59553bb01404600bdbcbbe
- Fix Xcode 10 errors relating to third-party https://github.com/facebook/react-native/commit/b44c5ae92eb08125d466cf151cb804dabfbbc690
- OkHTTP update https://github.com/facebook/react-native/commit/10fc548809cc08db209ae6696b723341925137d1
- When paddingStart is 0, it should override paddingHorizontal https://github.com/facebook/react-native/commit/f90c9b5292aa275854d3c0b579b340e8adda770c
- Fix reload for Image views in Android https://github.com/facebook/react-native/commit/5d414665ea67dd2a987c4822803aea5e6212c7e2
- Avoid cleaning up ReactRootView content when reactContext is destroyed https://github.com/facebook/react-native/commit/9817f85defe3cc900a66dee968b446223a0aa11c
- Uninstalling native FabricUIManager when reloading RN screen https://github.com/facebook/react-native/commit/ca3a6e8f130523a00249e3cd2e3d79341bce03b7
- Cleaning up imports in ViewGroupManager https://github.com/facebook/react-native/commit/082a869daef3cf602a088d0418c185279052b8c3
- Fabric: Custom border rendering on a separate CALayer https://github.com/facebook/react-native/commit/c8b6d606a0ad7111ed9c5f11bb5dee0b2c72af0a
- Update flow to v0.83 https://github.com/facebook/react-native/commit/7b150690b65a65d55c51d875bcbe4adf04cd67dd

**Comment by kelset** [comment] 2018-10-15 08:14
@radeno:
* the NDK one is already in 0.57.3
* You link a couple of Fabric related commits, I don't understand why we should cherry-pick those
* Unless there is a strong need for new Flow I don't think we should bump it in a patch-level release

**Comment by radeno** [comment] 2018-10-15 09:17
@kelset 
You are right about all points. My post is updated. So slimmer.

**Comment by yinhangfeng** [comment] 2018-10-15 13:04
0.57.3 android have a accessibility role crash issue https://github.com/facebook/react-native/issues/21754
it happens because incomplete cherry-pick from master https://github.com/facebook/react-native/issues/21754#issuecomment-429577266

**Comment by kelset** [comment] 2018-10-15 13:33
Hey @yinhangfeng thanks for pointing that out - if I understand correctly, we need to cherry pick these two 

- https://github.com/facebook/react-native/commit/1f96ff62cf786f93c91e6625bf2b819077902251
- https://github.com/facebook/react-native/commit/139559fc0716a9ab7b78c9524df5eb295d882547

to fix it right?

( cc @peat-psuwit)

**Comment by kelset** [comment] 2018-10-16 09:05
@janhesters as mentioned **way too many times** across these issues, **please** keep the conversation on commits already on master.

That said, on testing, there are things can could be done via PRs like [this](https://github.com/facebook/react-native/issues/19859#issuecomment-427685997) to help with it. And also you could submit PRs to the changelog: there is a "known issue" section precisely for those kind of scenarios.

**Comment by janhesters** [comment] 2018-10-16 10:39
@kelset I'm sorry, my mistake.

I think I'm not good enough create a PR and fix this issue (I wouldn't even know where to start). But I'm gonna do a PR for the changelog. Thank you! 😊

**Comment by mikemorris** [comment] 2018-10-16 16:15
Requesting https://github.com/facebook/react-native/commit/b44c5ae92eb08125d466cf151cb804dabfbbc690 for Xcode 10 support

**Comment by radeno** [comment] 2018-10-17 08:34
Another posible fixes to cherry-pick:
- Android: Fix pull to refresh refresh component clipping on Android https://github.com/facebook/react-native/commit/8a3a0ad2d0f894a3d8c1e403a9336dab17c2dde8
- RN: ListView requestAnimationFrame leak https://github.com/facebook/react-native/commit/70b5eb3aa27822fa11571c3d8d3628ecf03268ab
- Android: Fix DynamicFromMap object pool synchronization on Android https://github.com/facebook/react-native/commit/b0d68c0bb971a44dfdf7722682933f1e96e1cd45
- Android: Back out "[react-native][PR] Rounded corner rendering fixed on Android N." https://github.com/facebook/react-native/commit/bb407fa1ec0bd0367373961fdc0e840150840068
- iOS: Fix issue when inserting text at 0 when maxLength is set https://github.com/facebook/react-native/commit/36507e4a3c2fa58dcfdc9bd389b37536c66006d0

**Comment by youngjuning** [comment] 2018-10-17 20:31
```js
// @name Make ReactNative Great Again
// @description Allows you to enable support for JSX files, and `.mjs` files which is the new node standard
// @source http://www.fallingcanbedeadly.com/posts/enabling-react-native-jsx-extension
// @issues https://github.com/airbnb/javascript/issues/982
// @issues https://github.com/facebook/metro/issues/248
// @note One caveat, The `index.js` file in the root of your project has to be `.js`.
module.exports = {
  getSourceExts: () => ['jsx', 'mjs'],
}
```

is not work on 0.57.3

**Comment by mikemorris** [comment] 2018-10-17 23:51
- Android `textTransform` style support https://github.com/facebook/react-native/commit/22cf5dc5660f19b16de3592ccae4c42cc16ace69

**Comment by janicduplessis** [comment] 2018-10-19 03:18
https://github.com/facebook/react-native/commit/b0d68c0bb971a44dfdf7722682933f1e96e1cd45 fixes a crash that happens with react-native-svg (and possibly others) on Android.

**Comment by kelset** [comment] 2018-10-19 08:18
Thanks everyone, I'll try to review & finalise the list of cherry-picks today & trigger the release this weekend (has been sick for the past two days 🤢).

**Comment by Titozzz** [comment] 2018-10-19 08:36
Heya, https://github.com/facebook/react-native/commit/fd744dd56ca183933a67e8398e1d20da14a31aab might be interesting !

I know that some folks at https://github.com/archriss/react-native-snap-carousel/issues/203 would enjoy it 😄

**Comment by eldh** [comment] 2018-10-19 12:10
Would love to see https://github.com/facebook/react-native/commit/fa6035bda6c606868977179534cb941f26fbdb9 get into next release. It should fix testing with Appium (see https://github.com/facebook/react-native/issues/21238)

**Comment by kelset** [comment] 2018-10-19 12:29
@eldh that commit is already in 0.57.3 -> https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#android-specific-fixes

**Comment by eldh** [comment] 2018-10-19 13:18
Awesome, don't mind me then 😄

**Comment by kelset** [comment] 2018-10-19 16:13
Hey everyone - based on the list of commits listed above (plus a few more) I attempted a cherry-pick test locally to prep 0.57.4. It wasn't either easy or funny, so I didn't end up pushing to the remote branch what I've done locally.

Here's the breakdown, so that either myself or @hramos or @grabbou can pick it up quickly again - and we can discuss if we want to proceed with a subset of these commits or something.

I've managed to cherry-pick and test with everything ✅ these commits:

- the fix described [here](https://github.com/react-native-community/react-native-releases/issues/48#issuecomment-429872953) which actually triggers a conflict on [AccessibilityDelegateUtil](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/AccessibilityDelegateUtil.java) but copy/pasting the version from master is basically a valid way to correct the conflict so I went with that
- [Do not use fbjs/emptyObject](https://github.com/facebook/react-native/commit/75416553981a63e34635492c768c5a7763bf687b)
- [Fix crashes on invalid regex](https://github.com/facebook/react-native/commit/298f14da1210460b3e25c6002e8d1aa5f7b4e0ef)
- [Fix Xcode 10 errors relating to third-party](https://github.com/facebook/react-native/commit/b44c5ae92eb08125d466cf151cb804dabfbbc690)
- [Consolidate native dependencies versions](https://github.com/facebook/react-native/commit/ba608a2db786a8e983a6e30b31662fac254286c0)
- [bump okhttp3 to 3.11](https://github.com/facebook/react-native/commit/10fc548809cc08db209ae6696b723341925137d1)
- [Fix DynamicFromMap object pool synchronization](https://github.com/facebook/react-native/commit/b0d68c0bb971a44dfdf7722682933f1e96e1cd45)
- [Fix pull to refresh refresh component clipping on Android](https://github.com/facebook/react-native/commit/8a3a0ad2d0f894a3d8c1e403a9336dab17c2dde8)
- [Remove TimerMixin from ListView](https://github.com/facebook/react-native/commit/8ceb1586ee596a1bdf44bbb8e4c6ab54cbaa7c8b)
- [ListView requestAnimationFrame leak](https://github.com/facebook/react-native/commit/70b5eb3aa27822fa11571c3d8d3628ecf03268ab)
- [Back out "[react-native][PR] Rounded corner rendering fixed on Android N."](https://github.com/facebook/react-native/commit/bb407fa1ec0bd0367373961fdc0e840150840068)
- [Fix issue when inserting text at 0 when maxLength is set](https://github.com/facebook/react-native/commit/36507e4a3c2fa58dcfdc9bd389b37536c66006d0)
- [Bump xcode@1.0.0](https://github.com/facebook/react-native/commit/b9514995a26b4c3f6d555257740457dd4d6cfeae)
- [Text: send metrics after rendering (iOS)](https://github.com/facebook/react-native/commit/64a52532fe88b482ae4b998133d340e6e1141a0f)
- [Android: Send <Text> metrics in onTextLayout events](https://github.com/facebook/react-native/commit/737f93705ca8b5d3fdd207f870cf27adcf1e885b)
- [Use TextLegend example in Android as well](https://github.com/facebook/react-native/commit/335927db44fe47e20db4503a1ab5fcf8d62144a8)
- [Fix onTextLayout metrics on Android when using alignText](https://github.com/facebook/react-native/commit/1c240ae898e26534b8d9a09a334dec02e96faa05)
- [Allow specifying iOS version for run-ios with simulator option](https://github.com/facebook/react-native/commit/0fab27cbaca57b90119ab36104af4d0b3052ae30)
- [Relax the requirement that lazy module cannot be initialized on the main thread](https://github.com/facebook/react-native/commit/dbc864c9cd95f9df268d85a642742e84e2360db4)
- [Add deprecation notice to SwipeableListView](https://github.com/facebook/react-native/commit/99471f87b944b26bbdaa0fb0881db91c1118b741)
- [Cleaning up imports in ViewGroupManager](https://github.com/facebook/react-native/commit/082a869daef3cf602a088d0418c185279052b8c3)
- [Android textTransform style support](https://github.com/facebook/react-native/commit/22cf5dc5660f19b16de3592ccae4c42cc16ace69)

Aside from those (and here starts the complex stuff) the [React sync for revisions d836010...4773fdf](https://github.com/facebook/react-native/commit/8325e09e5cd8538fded1b5a1b4fff1854e17eb22) adds a warning about context, more precisely

> Deprecate context object as a consumer and add a warning message

And I'm pretty confident we don't want to spam it to everyone.

THEN, I also wanted to cherry pick those:

- [Fix rounding of negative numbers](https://github.com/facebook/react-native/commit/af8c69ecf70fa6cabeb6a76ff2d0f9362e18662e)
- [When paddingStart is 0, it should override paddingHorizontal](https://github.com/facebook/react-native/commit/f90c9b5292aa275854d3c0b579b340e8adda770c)

But they forced me to get into the spiral of these commits

- [Remove Node 10 check](https://github.com/facebook/react-native/commit/888474f76521901ccf3a2e230d7b7519b4c781d5)
- [Add missing copyright headers](https://github.com/facebook/react-native/commit/fe4f03517cd6248a163cab37369474908827c2d6)
- [Update copyright headers to yearless format](https://github.com/facebook/react-native/commit/1151c096dab17e5d9a6ac05b61aacecd4305f3db)

at least, and then everything was a mess of conflicts so I gave up of getting them in.

Lastly, other two I wanted to cherry pick but had conflicts not simple to fix

- [use requireActual and requireMock from jest instead of require](https://github.com/facebook/react-native/commit/5e997f9d51770224cbb6bf938739b56e1a7fa3e5)
- [Avoid calling lazilyLoadView when running in the debugger](https://github.com/facebook/react-native/commit/4f757095a8fdf28c6d59553bb01404600bdbcbbe)

---

So, after all this, I believe that we should proceed with a 0.57.4 with the first list I presented.
LMK

**Comment by matthargett** [comment] 2018-10-19 16:29
It looks like the noisiness of that React Context warning was lessened in a later commit:
https://github.com/facebook/react/commit/9ea4bc6ed607b0bbd2cff7bbdd4608db99490a5f

But if we don't have a way forward with React 16.6 stable, then I would propose reverting the React sync cherry picks from before and staying on 16.5 for the rest of the 0.57 releases. Taking an LTS onto a React alpha make me queasy, but leaving it on a React alpha is not great and gives me flashbacks to React Native 0.43.

**Comment by fungilation** [comment] 2018-10-19 16:46
Thanks for all the cherry picks @kelset! Hope you are recovering.

On React alpha, I for one don't want to upgrade to RN 0.57.3 because of it. As a matter principle, RN having no alpha or beta labeling shouldn't ever depend on alpha/beta versions of critical components. Why the rush? Let React 16.6 stabilize before cherry picking all the sync commits associated.

**Comment by a-tarasyuk** [comment] 2018-10-19 18:04
@kelset Thanks for the detailed update, and for your efforts to prepare this release. I hope that [Fix Xcode 10 errors relating to third-party](
https://github.com/facebook/react-native/commit/b44c5ae92eb08125d466cf151cb804dabfbbc690) will be merged to 0.57.4 ;) - it contains many changes, however, it can resolve annoying issues with the new Xcode.

**Comment by kelset** [comment] 2018-10-20 12:16
Thanks for everyone's feedback.

Related to the React alpha issue: I understand, but we are talking about an alpha of a minor version update, which is less likely to create issues (I haven't found any during my time with 0.57.3 in our prod app nor during my testing).

Since it's the weekend and my test yesterday wasn't quick nor easy, here's my proposal for now: this coming week there's ReactConf (October 25 & 26). So we'll soon have a clearer idea of when 16.6.0 will be out: I expect (but have no knowledge) that it will be out during the event, but if that's not the case (ex. they decide to release it in a month) we'll reverse the React sync.

This will mean delay the release of 0.57.4 of (at least) another week.

Or, we do a 0.57.4 with the "already tested" subset of commits I listed above and then for 0.57.5 we consider the 16.5.0 rollback (which means that people can't use React 16.5.2 btw).

LMK

**Comment by fungilation** [comment] 2018-10-20 13:01
Since what's done is done and I've said my piece regarding syncing with alpha, I'm for waiting another week if React 16.6.0 may likely be out then. Least work option, unless it's not out then.

**Comment by a-tarasyuk** [comment] 2018-10-20 15:39
In my opinion better to release RN which will work correctly with stable React version. _(16.5.2 or 16.6.0)_. Waiting one week to have a stable RN version which will with stable React _(does not matter 16.5.* or 16.6.*)_ version is absolutely OK.

**Comment by fungilation** [comment] 2018-10-20 17:06
You/I have RN 0.57.2 on React 16.5.0.

**Comment by ikesyo** [comment] 2018-10-21 16:48
I want the following to be cherry-picked

- Re-introduce UIImplementationProvider https://github.com/facebook/react-native/commit/b002df945b267c6e36aa1041397ffd1c73167037

**Comment by ahce** [comment] 2018-10-21 18:08
Is possible RN 0.57.4 with React 16.5.0?

**Comment by grabbou** [comment] 2018-10-22 12:55
As a matter of principle, I think we shouldn't publish a stable release of React Native that depends on an alpha version of React (even if that's an unstable release of a minor bump - there's always policies at companies). If this was a release candidate, I would say it's acceptable.

I would reverse the React sync and release next version as soon as possible. Even if a new release of React is out during the event, I am still not sure how long it will take for the sync commit to land. If that's really a lot of work, waiting for 3 days will not hurt anyone I guess.

**Comment by gwmccull** [comment] 2018-10-22 17:04
@grabbou I'm in  100% agreement about not using an alpha of React.  I had to do the upgrade to the version of React Native that used React 16 alpha (might have been 44?).  It was terrible.  Enzyme didn't support the alpha version of React and a lot of other libraries were broken

I don't think any new feature of React is worth that pain

**Comment by mikemorris** [comment] 2018-10-23 21:14
- Android Gradle plugin 3.2 directory path fix https://github.com/facebook/react-native/commit/ff084a4e8071adb4ff6198b32aa8a7e8e29cca1c

**Comment by ikesyo** [comment] 2018-10-23 23:04
@mikemorris That is already in 0.57.2 https://github.com/facebook/react-native/commit/a4fed6e203efd481175e61b7d2aa1c2b037a4279.

**Comment by fungilation** [comment] 2018-10-24 05:13
Well, I see React 16.6.0 already out.

**Comment by dvicory** [comment] 2018-10-24 21:11
An extra vote towards cherry-picking https://github.com/facebook/react-native/commit/b002df945b267c6e36aa1041397ffd1c73167037. We need this for react-native-navigation.

**Comment by ikesyo** [comment] 2018-10-25 13:34
- Quote "$NODE_BINARY" in react-native-xcode.sh https://github.com/facebook/react-native/commit/7d4e94edccfc2f642fcbd1d6aa00756f02e3a525

**Comment by matt-oakes** [comment] 2018-10-25 15:14
It would be good to get this merged PR cherry-picked as the issue is causing crashes on Android phone:

PR: https://github.com/facebook/react-native/pull/20913
Commit: https://github.com/facebook/react-native/commit/09c78fe968e1bb71108c4058e76ebf70178e5a8b

**Comment by kelset** [comment] 2018-10-25 17:47
hey everyone, thanks for all the feedback and participation. CircleCI was stuck again (and I was really busy) so I preferred to move forward with the set of commits I have already tested.

0.57.4 is out, the new issue is here -> https://github.com/react-native-community/react-native-releases/issues/54

(I've already added the two newest commits requested there)

**Closed by kelset** 2018-10-25 17:47 UTC
Labels: backport request, stable
