### ISSUE TITLE
0.59.3  Text component on Android getting other side on textAlign

### ISSUE THREAD

**Issue by tamirrab** [react-native-community/react-native-releases#110] opened 2019-04-02 15:57 UTC
Hi
Text:
on Android only, textAlign: "right" doing "left" instead of right.
and "left" doing "right" instead of left.
only on 0.59.3 and only on Android

**Comment by mikehardy** [comment] 2019-04-02 16:16
This isn't the main repo, I think @kelset meant the facebook/react-native repo, not react-native-releases

That said, this looks directly related to the RTL changes https://github.com/facebook/react-native/commit/871290f (from https://github.com/facebook/react-native/releases), and I'm guessing it's because whatever device you checked it on had an RTL locale set but this wasn't ever expressed until 0.59.3?

That's almost a breaking change really, if I'm correct, to have text direction change in a patch release...

**Comment by tamirrab** [comment] 2019-04-02 16:19
There is a different only on android and only from changing from 0.59.2 to 0.59.3
The same device and same repository 

On iOS it’s OK

**Comment by mikehardy** [comment] 2019-04-02 16:24
Right, you updated react-native, so you might check the 0.59.2 to 0.59.3 changelog, it would be evident iOS wouldn't change, because there were no changes there. https://github.com/facebook/react-native/compare/v0.59.2...v0.59.3

**Comment by tamirrab** [comment] 2019-04-02 16:26
So how can I create an issue to fix that?

**Comment by mikehardy** [comment] 2019-04-02 16:31
https://github.com/facebook/react-native/issues

you may be able to work around this with your text properties though. The upstream change was the right thing to do, it is just that your app wasn't expecting RTL to actually *work* and it is now.

**Comment by tamirrab** [comment] 2019-04-02 16:34
I think there is an issue because "right" on LTR need to be on the right side.
on iOS is in the right side.
on android 0.59.2 is in the right side
on android 0.59.3 is in the LEFT side
something is not good

**Comment by renalpraba** [comment] 2019-04-04 01:51
@tamirrab I think it's better to close this as you have open another one and already tracked reproducible in the [main repo](https://github.com/facebook/react-native/issues/24267)

**Comment by turnrye** [comment] 2019-04-04 02:02
Thanks for the link to the main repo -- I'm closing this here since it's not related to the release process.

**Closed by turnrye** 2019-04-04 02:02 UTC
